"""Data only: passwords rejected outright by the server-side password policy.

Not an attempt at the leaked-password-corpus problem (that needs an external
source — e.g. HaveIBeenPwned's k-anonymity API — and is explicitly out of
scope here). This is a short, curated list of the passwords real people
actually type first: English keyboard-mashes and dictionary classics, plus
their Russian equivalents — both the Cyrillic words themselves and the same
finger-pattern typed on a ЙЦУКЕН layout (``qwerty`` -> ``йцукен``).

Matching is case-insensitive (`app.services.password_policy` casefolds
before lookup) — this set is stored lower-cased already so a straight `in`
check is enough.
"""

_ENGLISH: tuple[str, ...] = (
    "123456",
    "1234567",
    "12345678",
    "123456789",
    "1234567890",
    "12345",
    "123123",
    "1231231234",
    "111111",
    "1111111",
    "11111111",
    "000000",
    "00000000",
    "654321",
    "696969",
    "777777",
    "888888",
    "121212",
    "112233",
    "123321",
    "1q2w3e4r",
    "1q2w3e4r5t",
    "1qaz2wsx",
    "qwerty",
    "qwerty123",
    "qwerty1",
    "qwertyuiop",
    "qweasdzxc",
    "qazwsx",
    "asdfgh",
    "asdfghjkl",
    "zxcvbnm",
    "zxcvbn",
    "password",
    "password1",
    "password123",
    "passw0rd",
    "pa55word",
    "letmein",
    "letmein123",
    "welcome",
    "welcome1",
    "welcome123",
    "monkey",
    "monkey123",
    "dragon",
    "dragon123",
    "master",
    "master123",
    "shadow",
    "superman",
    "batman",
    "spiderman",
    "iloveyou",
    "iloveyou1",
    "loveyou",
    "trustno1",
    "sunshine",
    "princess",
    "princess1",
    "football",
    "football1",
    "baseball",
    "basketball",
    "soccer",
    "hockey",
    "michael",
    "jennifer",
    "jordan",
    "hunter",
    "hunter2",
    "ranger",
    "buster",
    "george",
    "harley",
    "andrew",
    "charlie",
    "daniel",
    "matthew",
    "abc123",
    "abcd1234",
    "abcdef",
    "abcdefg",
    "abcdefgh",
    "abcabc123",
    "a1b2c3",
    "starwars",
    "startrek",
    "pokemon",
    "minecraft",
    "fortnite",
    "freedom",
    "whatever",
    "ninja",
    "mustang",
    "cheese",
    "chocolate",
    "computer",
    "internet",
    "biteme",
    "access",
    "access14",
    "flower",
    "summer",
    "summer123",
    "winter",
    "winter123",
    "autumn",
    "spring",
    "spring123",
    "ashley",
    "amanda",
    "michelle",
    "nicole",
    "jessica",
    "elizabeth",
    "thomas",
    "robert",
    "richard",
    "joshua",
    "letme1n",
    "changeme",
    "change123",
    "temp1234",
    "temppass",
    "test1234",
    "testtest",
    "test123",
    "guest",
    "guest123",
    "admin123",
    "adminadmin",
    "root1234",
    "user1234",
    "default",
    "newpassword",
    "newpass123",
    "mypassword",
    "mypass123",
    "hello123",
    "helloworld",
    "letsgo123",
    "gogogo123",
    "iamgroot",
    "asdasd123",
    "asdzxc123",
    "qweqwe123",
    "1234qwer",
    "qwer1234",
    "1q2w3e",
    "zaq12wsx",
    "xsw23edc",
    "p@ssword",
    "p@ssw0rd",
    "passw@rd",
    "passwd",
    "passwd123",
    "love123",
    "forever",
    "forever21",
    "angel123",
    "angel1",
    "sweety",
    "sweetheart",
    "babygirl",
    "babyboy",
    "cutiepie",
    "iloveu",
    "iloveu2",
    "godislove",
    "jesus1",
    "christ123",
    "family123",
    "friends",
    "bestfriend",
    "nopassword",
    "nothing123",
    "blahblah",
)

# Cyrillic (типичные слова + фразы, набранные по-русски).
_RUSSIAN_CYRILLIC: tuple[str, ...] = (
    "пароль",
    "пароль1",
    "пароль123",
    "парольпароль",
    "пароль12345",
    "яблоко",
    "яблоко123",
    "привет",
    "привет123",
    "приветик",
    "здравствуй",
    "любовь",
    "любовь123",
    "любимая",
    "любимый",
    "солнышко",
    "солнце123",
    "котенок",
    "котёнок",
    "кошечка",
    "малышка",
    "малыш123",
    "ромашка",
    "звездочка",
    "звёздочка",
    "радуга",
    "family",
    "семья123",
    "мамапапа",
    "качество",
    "россия",
    "россия123",
    "москва",
    "москва123",
    "простопароль",
    "секретсекрет",
    "секрет123",
    "секретный",
    "введипароль",
    "changeme123",
    "неважно123",
    "ктототам",
    "пятьшесть",
    "одиндва",
    "цифры123",
    "буквы123",
    "новыйпароль",
    "старыйпароль",
    "временныйпароль",
    "детство",
    "молодость",
    "вечность",
    "навсегда",
    "судьба",
    "надежда",
    "надежда123",
    "победа",
    "победа123",
    "свобода",
    "мечта123",
)

# Russian words spelled out with Latin letters (no keyboard-layout trick,
# just a transliteration — "parol", "privet", "lyubov").
_RUSSIAN_TRANSLIT: tuple[str, ...] = (
    "parol",
    "parol123",
    "parolparol",
    "privet",
    "privet123",
    "lyubov",
    "lyubimaya",
    "solnyshko",
    "kotenok",
    "malyshka",
    "moskva",
    "rossiya",
    "sekret123",
)

# Same finger-pattern as an English classic, typed while the keyboard is set
# to a Russian (ЙЦУКЕН) layout — the OS maps the physical keys to Cyrillic
# glyphs, so "qwerty" comes out as "йцукен", "12345" stays "12345", etc.
_RUSSIAN_LAYOUT: tuple[str, ...] = (
    "йцукен",
    "йцукенг",
    "йцукенгш",
    "йцукенгшщз",
    "фыва",
    "фывапролд",
    "фывапролдж",
    "ячсмить",
    "ячсмитьб",
    "йфячыа",  # "1qaz2wsx" pattern on ЙЦУКЕН
    "запароль",  # "zaq1" then "пароль"-style keymash variant, common typo-word
    "пороль",  # extremely common misspelling of "пароль"
    "паролькубика",
)

COMMON_PASSWORDS: frozenset[str] = frozenset(
    word.casefold()
    for word in (*_ENGLISH, *_RUSSIAN_CYRILLIC, *_RUSSIAN_TRANSLIT, *_RUSSIAN_LAYOUT)
)
