// Pure phase reducer for the solo solve ritual (§5.1 minus opponent). No DOM, no
// timers — fully unit-testable. The orchestrator (useSoloSession) feeds it actions
// derived from the camera/hands loop and reads back the phase.
//
// Phase order: loading → walkthrough → verify → armed → solving → result.
//
// Timer gate (plan #3): `solve_start` only transitions when the phase is "armed"
// (which is only reached via verify_ok, i.e. scrambleVerified). The FSM can never
// advance the ritual past HANDS_IN_ZONE into a timed solve on an unverified scramble.
//
// Elapsed timebase (plan #4/#6): elapsedMs = stopT − startT, where both are the
// frame timestamps (o.t) that produced solve_start/solve_stop. Never a React tick.

export type SoloPhase =
  | "loading" // generating scramble / loading cubing
  | "walkthrough" // stepping through the scramble
  | "verify" // collecting 6 faces to check the scramble
  | "armed" // scramble verified; FSM may now arm/start the timer
  | "solving" // timer running
  | "result"; // fixed time or DNF

export interface SoloState {
  phase: SoloPhase;
  scrambleVerified: boolean;
  startT: number | null;
  stopT: number | null;
  elapsedMs: number;
  mismatch: { face: string; count: number } | null;
  dnf: boolean; // true when the solve ended by abort (detection lost)
}

export const initialSoloState: SoloState = {
  phase: "loading",
  scrambleVerified: false,
  startT: null,
  stopT: null,
  elapsedMs: 0,
  mismatch: null,
  dnf: false,
};

export type SoloAction =
  | { type: "scramble_ready" }
  | { type: "goto_verify" }
  | { type: "back_to_walkthrough" }
  | { type: "verify_ok" }
  | { type: "verify_mismatch"; face: string; count: number }
  | { type: "solve_start"; t: number }
  | { type: "solve_stop"; t: number }
  | { type: "abort" }
  | { type: "again" };

export function soloReducer(s: SoloState, a: SoloAction): SoloState {
  switch (a.type) {
    case "scramble_ready":
      // Only leave the loading gate; ignore if the ritual already moved on.
      return s.phase === "loading" ? { ...s, phase: "walkthrough" } : s;

    case "goto_verify":
      return s.phase === "walkthrough"
        ? { ...s, phase: "verify", mismatch: null }
        : s;

    case "back_to_walkthrough":
      return s.phase === "verify"
        ? { ...s, phase: "walkthrough", mismatch: null, scrambleVerified: false }
        : s;

    case "verify_ok":
      return s.phase === "verify"
        ? { ...s, phase: "armed", scrambleVerified: true, mismatch: null }
        : s;

    case "verify_mismatch":
      // Stay in verify; the timer stays un-armed (scrambleVerified false).
      return s.phase === "verify"
        ? { ...s, scrambleVerified: false, mismatch: { face: a.face, count: a.count } }
        : s;

    case "solve_start":
      // GATE: never start timing unless armed + verified.
      return s.phase === "armed" && s.scrambleVerified
        ? { ...s, phase: "solving", startT: a.t, stopT: null, elapsedMs: 0 }
        : s;

    case "solve_stop":
      return s.phase === "solving" && s.startT !== null
        ? {
            ...s,
            phase: "result",
            stopT: a.t,
            elapsedMs: a.t - s.startT,
            dnf: false,
          }
        : s;

    case "abort":
      // Detection lost. Mid-solve → DNF result. Otherwise (armed, not started)
      // just drop any partial start; the FSM re-arms.
      if (s.phase === "solving" && s.startT !== null) {
        return {
          ...s,
          phase: "result",
          startT: null,
          stopT: null,
          elapsedMs: 0,
          dnf: true,
          scrambleVerified: false,
        };
      }
      return s.phase === "armed" ? { ...s, startT: null } : s;

    case "again":
      // Fresh cycle without a page reload — new scramble regenerated by caller.
      return { ...initialSoloState };
  }
}
